### ISSUE TITLE
Better custom color picker

### ISSUE THREAD

**Issue by gammelalf** [pnp-zone/pnp-zone#12]
Not random html5 default
something like gimp xD

**Comment by myOmikron** [comment]
![image](https://user-images.githubusercontent.com/39948112/150650578-e2623b75-baf6-48f7-8146-fba34d649b93.png)

That's my dream <3

**Comment by gammelalf** [comment]
![image](https://user-images.githubusercontent.com/31348226/150688998-775a06ac-8e5a-4076-8aba-e919127ca680.png)

Good enough?

**Comment by myOmikron** [comment]
I'd rather like to had the textinput in the formats:
 `#FFFFFFAA` or `FFFFFFAA` or `#FFFFFF` or `FFFFFF` or `#FFF` or `FFF`
then to force the user giving a correct rgba.

**Comment by gammelalf** [comment]
The textinput accepts any valid css color:
- hex `#FF0000` (also without hash)
- rgb/rgba `rgb(255, 0, 0)`
- hls/hlsa `hls(0, 100%, 50%)` (also decimal numbers instead of percentages)
- names `red`

when adjusting sliders it will output the current color to this field. the format depends on the slider who was last to be used. (before the screenshot I used an rgb slider)

**Comment by gammelalf** [comment]
would you prefer a unified output format or maybe no output at all?

**Comment by myOmikron** [comment]
I'd prefer Hex as output format, if alpha was used (everything other than 100%) as long format `#RRGGBBAA`
