### ISSUE TITLE
Add an option to set coordinates in board

### ISSUE THREAD

**Issue by myOmikron** [pnp-zone/pnp-zone#15]
Another option would be to return to [0,0]

**Comment by gammelalf** [comment]
Where do you suggest to put the ui element?
The context menu?

**Comment by myOmikron** [comment]
I'd suggest the left sidebar

**Comment by gammelalf** [comment]
In a "navigation" or "user tools" tab?

**Comment by myOmikron** [comment]
Latter. I think just a option to set coordinates would be too much wasted space
