### ISSUE TITLE
Fix websockets

### ISSUE THREAD

**Issue by myOmikron** [pnp-zone/pnp-zone#18]
You may wanna introduce a form of `alive` packets to check the websocket state

**Comment by myOmikron** [comment]
Still sort of broken.
Some player can see each others cursor, but only in groups ( a can see b, b -> a, c can see d, d can see c)

Updates don't get pushed to the players, but they are sent to the server. After refreshing, the update is available for all players

**Comment by myOmikron** [comment]
Have you added an `alive` packet to check the websocket? @gammelalf

**Comment by gammelalf** [comment]
Pretty sure it was the misconfigured channel_layer.
Don't use InMemory
